[package]
name = "frequency_merge"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40", features = ["full"] }
tokio-util = { version = "0.7.12" }
clap = { version = "4.5.20", features = ["derive"] }
